# Generated by Django 4.2.2 on 2023-06-11 23:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TurneroWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_Especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'EspecialidadMédica',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni_paciente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'paciente usuario',
                'verbose_name_plural': 'pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.AlterModelOptions(
            name='especialista',
            options={'verbose_name': 'EspecialistaMédico', 'verbose_name_plural': 'Especialistas'},
        ),
        migrations.AlterModelOptions(
            name='turnosporespecialista',
            options={'verbose_name': ' turnosParaEspecialistaMédico', 'verbose_name_plural': 'turnosPorEspecialistas'},
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='horariosDeAtencion',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='id_Turnos',
        ),
        migrations.RemoveField(
            model_name='turnosporespecialista',
            name='horarioDeTurno',
        ),
        migrations.CreateModel(
            name='ReservaDeTurno',
            fields=[
                ('id_Reserva', models.AutoField(primary_key=True, serialize=False)),
                ('dni_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurneroWeb.paciente')),
                ('id_Turnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurneroWeb.turnosporespecialista')),
            ],
            options={
                'verbose_name': ' Turnos reservados por pacientes',
                'verbose_name_plural': 'ReservasDeTurnos',
                'db_table': 'reservaDeTurno',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('hora', models.TimeField(default=datetime.datetime.now)),
                ('id_Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurneroWeb.reservadeturno')),
            ],
            options={
                'verbose_name': ' Pago de turns reservado por paciente',
                'verbose_name_plural': 'PagosDeTurnos',
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='HorarioDeAtencion',
            fields=[
                ('id_Horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_de_la_semana', models.CharField(max_length=45, verbose_name='Dia de la semana')),
                ('hora_inici', models.DateTimeField()),
                ('hora_fi', models.DateTimeField()),
                ('id_Especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurneroWeb.especialista')),
            ],
            options={
                'verbose_name': ' horariosSemanalesPorCadaEspecialista',
                'verbose_name_plural': 'HorariosDeAtención',
                'db_table': 'HorarioDeAtencion',
            },
        ),
        migrations.AddField(
            model_name='especialista',
            name='id_Especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TurneroWeb.especialidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnosporespecialista',
            name='id_Horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TurneroWeb.horariodeatencion'),
            preserve_default=False,
        ),
    ]
